name: 加载OpenAPI文件，生成对应的GoIN API描述格式
arguments: 0
loader: Json('test_data/opensanctions-opensanctions.json')

nodes:
  to_goin: web.openapi.FromOpenAPI
  group: Group(by='owner', emit_fast=False)
  to_openapi: web.openapi.ToOpenAPI
  print: Print
  count: Count(label='generated openapi')
  buffer: Buffer(buffer_size=3, mode='batch')
  writer: WriteJson('test_data/goin_model.jsonl')._set(buffer_size=1)
  writer2: WriteJson('test_data/openapi.jsonl')._set(buffer_size=5)
#  chain1: Chain(to_goin, writer, count)
#  chain2: Chain(to_goin, group, to_openapi, writer2, count)
  flat: Flat
  chain3: Chain(to_goin, buffer, flat, group, print)

processor: chain3
