name: 加载OpenAPI文件，生成对应的GoIN API描述格式
arguments: 0
finish_signal: True
loader: Json('test_data/opensanctions-openapi.json')

nodes:
  to_goin: iterator.web.openapi.FromOpenAPI
  group: Group(by='owner')
  to_openapi: iterator.web.openapi.ToOpenAPI
  print: Print
  count: Count
  writer: WriteJson('test_data/goin_model.jsonl')._set(buffer_size=1)
  writer2: WriteJson('test_data/openapi.jsonl')._set(buffer_size=5)
  chain1: Chain(to_goin, writer, count)
  chain2: Chain(to_goin, group, to_openapi, writer2, count)

processor: chain2
